title: Xyfrux Geocaching
collections:
  main:
    output: true
    permalink: /:title/
  geocaches:
    output: true
    permalink: /geocaches/:title/
  geocaches-wip:
    output: true
    permalink: /geocaches-wip/:title/
